// <auto-generated />
using System;
using FirearmStudio.Domain.Enums;
using FirearmStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirearmStudio.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629214646_FixCustomAccessTokenHookAmbiguity")]
    partial class FixCustomAccessTokenHookAmbiguity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "customer_type", new[] { "company", "individual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firearm_status", new[] { "in_storage", "inactive", "pending_transfer", "released" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invoice_status", new[] { "cancelled", "draft", "overdue", "paid", "sent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "licence_status", new[] { "expired", "renewal_due", "unknown", "valid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "card", "cash", "debit_order", "eft", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_status", new[] { "active", "cancelled", "released" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirearmStudio.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("AuthUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_auth_user_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_app_users_company_id");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_company_id_email");

                    b.ToTable("app_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_users_role", "role between 0 and 3");
                        });
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_audit_logs_app_user_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_audit_logs_company_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("province");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vat_number");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<CustomerType>("CustomerType")
                        .HasColumnType("customer_type")
                        .HasColumnName("customer_type");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdNumberCiphertext")
                        .HasColumnType("text")
                        .HasColumnName("id_number_ciphertext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("province");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vat_number");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customers_company_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Firearm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calibre")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("calibre");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("FirearmType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("firearm_type");

                    b.Property<string>("InternalReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("internal_reference");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("serial_number");

                    b.Property<FirearmStatus>("Status")
                        .HasColumnType("firearm_status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_firearms");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_firearms_company_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_firearms_customer_id");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_firearms_serial_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_firearms_status");

                    b.HasIndex("CompanyId", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_firearms_company_id_serial_number");

                    b.ToTable("firearms", (string)null);
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.FirearmLicence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("document_url");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<Guid>("FirearmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firearm_id");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("licence_number");

                    b.Property<DateOnly>("RenewalDueOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date")
                        .HasColumnName("renewal_due_on")
                        .HasComputedColumnSql("expires_on - 90", true);

                    b.Property<LicenceStatus>("Status")
                        .HasColumnType("licence_status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_firearm_licences");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_firearm_licences_company_id");

                    b.HasIndex("ExpiresOn")
                        .HasDatabaseName("ix_firearm_licences_expires_on");

                    b.HasIndex("FirearmId")
                        .HasDatabaseName("ix_firearm_licences_firearm_id");

                    b.HasIndex("RenewalDueOn")
                        .HasDatabaseName("ix_firearm_licences_renewal_due_on");

                    b.HasIndex("FirearmId", "LicenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_firearm_licences_firearm_id_licence_number");

                    b.ToTable("firearm_licences", null, t =>
                        {
                            t.HasCheckConstraint("ck_firearm_licences_date_range", "issued_on is null or issued_on <= expires_on");
                        });
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<DateOnly>("InvoiceMonth")
                        .HasColumnType("date")
                        .HasColumnName("invoice_month");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<InvoiceStatus>("Status")
                        .HasColumnType("invoice_status")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("vat_amount");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_invoices_company_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_invoices_status");

                    b.HasIndex("CompanyId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_company_id_invoice_number");

                    b.HasIndex("CustomerId", "InvoiceMonth")
                        .HasDatabaseName("ix_invoices_customer_id_invoice_month");

                    b.HasIndex("CompanyId", "CustomerId", "InvoiceMonth")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_company_id_customer_id_invoice_month");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_amounts", "subtotal >= 0 and vat_amount >= 0 and total = subtotal + vat_amount");
                        });
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FirearmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firearm_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invoice_lines");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_invoice_lines_company_id");

                    b.HasIndex("FirearmId")
                        .HasDatabaseName("ix_invoice_lines_firearm_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id");

                    b.ToTable("invoice_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_lines_amounts", "quantity > 0 and unit_price >= 0 and line_total >= 0");
                        });
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("payment_method")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_payments_company_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.StorageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirearmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firearm_id");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_rate");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("RackNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("rack_number");

                    b.Property<string>("SafeNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("safe_number");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_location");

                    b.Property<StorageStatus>("StorageStatus")
                        .HasColumnType("storage_status")
                        .HasColumnName("storage_status");

                    b.Property<DateOnly>("StoredFrom")
                        .HasColumnType("date")
                        .HasColumnName("stored_from");

                    b.Property<DateOnly?>("StoredUntil")
                        .HasColumnType("date")
                        .HasColumnName("stored_until");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_storage_records");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_storage_records_company_id");

                    b.HasIndex("FirearmId")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_records_active")
                        .HasFilter("storage_status = 'active'");

                    b.ToTable("storage_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_storage_records_date_range", "stored_until is null or stored_until >= stored_from");

                            t.HasCheckConstraint("ck_storage_records_monthly_rate", "monthly_rate > 0");

                            t.HasCheckConstraint("ck_storage_records_status_dates", "(storage_status = 'active' and stored_until is null) or (storage_status <> 'active' and stored_until is not null)");
                        });
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_users_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_app_users_app_user_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_companies_company_id");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Customer", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_companies_company_id");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Firearm", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firearms_companies_company_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Customer", "Customer")
                        .WithMany("Firearms")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firearms_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.FirearmLicence", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firearm_licences_companies_company_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Firearm", "Firearm")
                        .WithMany("Licences")
                        .HasForeignKey("FirearmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firearm_licences_firearms_firearm_id");

                    b.Navigation("Firearm");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_companies_company_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_companies_company_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Firearm", "Firearm")
                        .WithMany()
                        .HasForeignKey("FirearmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoice_lines_firearms_firearm_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_invoices_invoice_id");

                    b.Navigation("Firearm");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Payment", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_companies_company_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.StorageRecord", b =>
                {
                    b.HasOne("FirearmStudio.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_storage_records_companies_company_id");

                    b.HasOne("FirearmStudio.Domain.Entities.Firearm", "Firearm")
                        .WithMany("StorageRecords")
                        .HasForeignKey("FirearmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_storage_records_firearms_firearm_id");

                    b.Navigation("Firearm");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Firearms");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Firearm", b =>
                {
                    b.Navigation("Licences");

                    b.Navigation("StorageRecords");
                });

            modelBuilder.Entity("FirearmStudio.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
