<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FirearmStudio.Domain.Tests" />
    <InternalsVisibleTo Include="FirearmStudio.Infrastructure.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirearmStudio.Domain\FirearmStudio.Domain.csproj" />
  </ItemGroup>

</Project>
