<Project Sdk="Microsoft.NET.Sdk">

  <!-- TargetFramework / Nullable / ImplicitUsings come from Directory.Build.props -->

  <ItemGroup>
    <!-- Gives access to DI and IHttpContextAccessor without NuGet packages -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="DotNetEnv" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirearmStudio.Application\FirearmStudio.Application.csproj" />
  </ItemGroup>

</Project>
